[project]
name = "dspy-optimizer-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dspy>=2.6.27",
]

[dependency-groups]
dev = [
    "ruff>=0.11.13",
]
